version: 2
jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.6.1/stack-1.6.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.6.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.6.1-linux-x86_64/stack /usr/bin/stack
      - restore_cache:
          name: Restore Cached Dependencies
          key: timetask--{{ checksum ".circleci/config.yml" }}-{{ checksum "package.yaml" }}
      - run:
          name: Resolve and update dependencies
          command: stack setup
      - run:
          name: Install hlint
          command: sh ciLint.sh
      - run:
          name: Build the dependencies and the library
          command: stack --silent build
      - save_cache:
          name: Cache Build
          key: timetask--{{ checksum ".circleci/config.yml" }}-{{ checksum "package.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
            - ".local"
            - "/root/.stack"
      - run:
          name: Run Linter
          command: git ls-files | grep '\.l\?hs$' | xargs stack exec -- hlint -X QuasiQuotes -X NoPatternSynonyms "$@"

workflows:
  version: 2
  main:
    jobs:
      - build-test
