version: 2
jobs:
  build-test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          key: timetask--{{ checksum ".circleci/config.yml" }}-{{ checksum "package.yaml" }}
      - run: sudo dir
      - run: 
          name: install stack
          command: sudo sh ~/getStack.sh

      - run:
          name: Resolve and update dependencies
          command: stack setup
      - run:
          name: Build the dependencies and the library
          command: stack --silent build
      - save_cache:
          name: Cache Build
          key: timetask--{{ checksum ".circleci/config.yml" }}-{{ checksum "package.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
            - ".local"
            - "/root/.stack"
      - run:
          name: Run Linter
          command: sh ciLint.sh

workflows:
  version: 2
  main:
    jobs:
      - build-test
